import React, { useState } from 'react';
import { ArrowLeft, Check, Sparkles } from 'lucide-react';
import { motion } from 'framer-motion';
import PortfolioDetailsStep from './PortfolioDetailsStep';
import DesignPreferencesStep from './DesignPreferencesStep';
import StudioTopBar from './StudioTopBar';
import ReviewStep from './ReviewStep';
import { buildPortfolioPrompt } from './portfolioPrompt';

const INITIAL_DETAILS = { name:'',role:'',location:'',bio:'',targetAudience:'',primaryGoal:'',phone:'',contactEmail:'',resumeFile:null,skills:[],projects:[],experience:[],education:[],achievements:[],interests:[],socialLinks:{github:'',linkedin:'',twitter:'',instagram:'',kaggle:''},ctaText:'',ctaLink:'',images:[],videos:[] };
const INITIAL_DESIGN = { style:'modern',theme:'dark',animations:'subtle',primaryColor:'#b8935a',paletteId:'amber',palette:'#b8935a, #e8d9bf, #b4583a, #2f3436, #f1f1f1',typography:'grotesk',themeTouched:false,paletteTouched:false };
export default function PortfolioBuilder({onBack,onGenerate}){
 const [step,setStep]=useState(0),[details,setDetails]=useState(INITIAL_DETAILS),[design,setDesign]=useState(INITIAL_DESIGN),[generating,setGenerating]=useState(false);
 const generate=async()=>{setGenerating(true);try{await onGenerate(buildPortfolioPrompt(details,design),{details,design});}finally{setGenerating(false);}};
 if(step===1)return <DesignPreferencesStep websiteType="portfolio" design={design} onChange={setDesign} onBack={()=>setStep(0)} onNext={()=>setStep(2)} topBar={<StudioTopBar onBack={onBack} disabled={generating} title="Portfolio builder" step={step}/>}/>;
 return <div className="min-h-full bg-neutral-950 bg-[radial-gradient(ellipse_70%_38%_at_50%_0%,rgba(124,58,237,.22),transparent)] text-white"><div className={`mx-auto px-5 pb-12 pt-24 md:px-8 md:pt-28 ${step===0?'max-w-6xl':'max-w-4xl'}`}><div className="mb-8 flex items-center justify-between"><button type="button" onClick={onBack} disabled={generating} className="inline-flex items-center gap-2 text-sm text-white/60 hover:text-white disabled:opacity-40"><ArrowLeft size={16}/> Website types</button><div className="inline-flex items-center gap-2 text-sm text-violet-200/80"><Sparkles size={15} className="text-violet-400"/> Portfolio builder</div></div><div className="mb-8 flex gap-4" aria-label="Portfolio builder progress">{['Details','Design','Review'].map((label,index)=><div key={label} className="flex-1"><div className={`h-1.5 rounded-full ${index<=step?'bg-[linear-gradient(90deg,#7c3aed,#a78bfa)]':'bg-white/10'}`}/><div className={`mt-2 flex justify-between text-[11px] ${index===step?'text-white':'text-white/35'}`}><span>{label}</span><span>Step {String(index+1).padStart(2,'0')}</span></div></div>)}</div><motion.div key={step} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.2}}>{step===0&&<PortfolioDetailsStep details={details} onChange={setDetails} onBack={onBack} onNext={()=>setStep(1)}/>} {step===2&&<div className="mx-auto max-w-4xl"><ReviewStep details={details} design={design} assets={{profileImage:null,resume:null,projectImages:[]}} onBack={()=>setStep(1)} onEditStep={setStep} onGenerate={generate} generating={generating}/></div>}</motion.div>{generating&&<div className="mt-5 flex items-center justify-center gap-2 text-xs text-white/40"><Check size={14} className="text-violet-400"/> Questionnaire locked while the real generation pipeline is running…</div>}</div></div>;
}
